services:
    app:
        build: .
        environment:
            REALM: prod
            REDIS_URL: "//redis:6379"
        links:
            - redis
        ports:
            - "8888:8888"

    redis:
        image: redis
